# Generated by Django 5.0.6 on 2024-09-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('about', models.TextField()),
                ('discount', models.IntegerField()),
                ('count', models.IntegerField()),
                ('oyiga_t', models.IntegerField()),
            ],
        ),
    ]
